added hashcode/equals + tests
smoketurner/dropwizard-consul pull request #33
Opened 2017-04-21 08:52 UTC by ryansmithevans

2017-04-21 19:05 UTC, jplock requested changes

2017-04-21 19:05 UTC, jplock commented on consul-core/pom.xml
> +            <groupId>org.hamcrest</groupId>
instead of hamcrest, can you use the assertj matchers that come with Dropwizard already?

2017-04-24 11:46 UTC, jplock approved these changes

2017-04-24 11:46 UTC, merged

2017-04-24 11:46 UTC, jplock commented
Thanks!

2017-04-24 12:07 UTC, ryansmithevans commented
:+1: