ACL Support for Consul
smoketurner/dropwizard-consul pull request #43
Opened 2018-02-26 15:37 UTC by jadams74

First stab at merging to your repo. Please let me know what changes I should make.

- regards

2018-02-26 20:01 UTC, jplock requested changes

2018-02-26 20:01 UTC, jplock commented on consul-core/src/main/java/com/smoketurner/dropwizard/consul/ConsulBundle.java
> +            if(getConsulAclToken() == null) {
above this line, why not start creating the `Consul.builder()`, then only if `getConsulAclToken()` isn't an empty `Optional`, you then do the headers stuff below?

2018-02-26 20:01 UTC, jplock commented on consul-core/src/main/java/com/smoketurner/dropwizard/consul/ConsulBundle.java
> +    public String getConsulAclToken() {
I'd make this return a `Optional<String>`

2018-02-26 20:01 UTC, jplock commented on consul-core/src/main/java/com/smoketurner/dropwizard/consul/ConsulFactory.java
> +            Map<String, String> headers = new HashMap<>();
this could probably be:

```
Map<String, String> headers = ImmutableMap.of(CONSUL_AUTH_HEADER_KEY, aclToken.get());
```

2018-02-27 15:03 UTC, jadams74 commented
@jplock requested changes are complete

2018-02-28 17:14 UTC, jplock approved these changes
I might clean this up a bit, but thanks for the contribution!

2018-02-28 17:14 UTC, merged